### ISSUE TITLE
Errors when running examples

### ISSUE THREAD

**Issue by dmitriz** [funkia/turbine#30]
Steps to reproduce:

```sh
git clone https://github.com/funkia/turbine/
cd turbine
yarn
cd examples/counters
yarn
npm run start
```

Output:

```sh
> turbine-counters-example@1.0.0 start /Users/dmitrizaitsev/Repos/turbine/examples/counters
> webpack-dev-server

Project is running at http://localhost:8080/
webpack output is served from /
ts-loader: Using typescript@2.3.2 and /Users/dmitrizaitsev/Repos/turbine/examples/counters/tsconfig.json
Hash: 359266e80baf3486ab11
Version: webpack 2.5.1
Time: 7789ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  869 kB       0  [emitted]  [big]  main
chunk    {0} bundle.js (main) 768 kB [entry] [rendered]
    [7] (webpack)/buildin/global.js 509 bytes {0} [built]
   [41] ./~/@funkia/jabz/dist/es/index.js 389 bytes {0} [built]
   [72] ./~/@funkia/hareactive/index.js 459 bytes {0} [built]
  [186] ./src/index.ts 1.64 kB {0} [built] [5 errors]
  [187] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
  [188] (webpack)-dev-server/client?http://localhost:8080 5.68 kB {0} [built]
  [206] ./~/core-js/fn/regexp/escape.js 107 bytes {0} [built]
  [386] ./~/core-js/shim.js 7.38 kB {0} [built]
  [398] ./~/regenerator-runtime/runtime.js 24.4 kB {0} [built]
  [426] ./~/strip-ansi/index.js 161 bytes {0} [built]
  [427] ./~/url/url.js 23.3 kB {0} [built]
  [429] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
  [430] (webpack)-dev-server/client/socket.js 897 bytes {0} [built]
  [432] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [443] multi (webpack)-dev-server/client?http://localhost:8080 babel-polyfill ./src/index.ts 52 bytes {0} [built]
     + 429 hidden modules

ERROR in /Users/dmitrizaitsev/Repos/turbine/src/component.ts
(34,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

ERROR in ./src/version4.ts
(44,3): error TS2322: Type 'Component<{} & OutputStream<{}> & BehaviorOutput<{}> & DefaultOutput>' is not assignable to type 'Component<CounterModelInput>'.
  Type '{} & OutputStream<{}> & BehaviorOutput<{}> & DefaultOutput' is not assignable to type 'CounterModelInput'.
    Property 'incrementClick' is missing in type '{} & OutputStream<{}> & BehaviorOutput<{}> & DefaultOutput'.

ERROR in ./src/version4.ts
(56,27): error TS2345: Argument of type '({incrementClick, decrementClick, deleteClick}: CounterModelInput, id: number) => IterableIterato...' is not assignable to parameter of type 'Model1<CounterModelInput, ReactivesObject, {}, number>'.
  Type 'IterableIterator<Now<Behavior<number>> | ({ count: any; } | { count: any; deleteS: Stream<number>...' is not assignable to type 'ModelReturn<ReactivesObject, {}>'.
    Type 'IterableIterator<Now<Behavior<number>> | ({ count: any; } | { count: any; deleteS: Stream<number>...' is not assignable to type 'Iterator<Now<any> | [ReactivesObject, {}]>'.
      Types of property 'next' are incompatible.
        Type '(value?: any) => IteratorResult<Now<Behavior<number>> | ({ count: any; } | { count: any; deleteS:...' is not assignable to type '(value?: any) => IteratorResult<Now<any> | [ReactivesObject, {}]>'.
          Type 'IteratorResult<Now<Behavior<number>> | ({ count: any; } | { count: any; deleteS: Stream<number>; ...' is not assignable to type 'IteratorResult<Now<any> | [ReactivesObject, {}]>'.
            Type 'Now<Behavior<number>> | ({ count: any; } | { count: any; deleteS: Stream<number>; })[]' is not assignable to type 'Now<any> | [ReactivesObject, {}]'.
              Type '({ count: any; } | { count: any; deleteS: Stream<number>; })[]' is not assignable to type 'Now<any> | [ReactivesObject, {}]'.
                Type '({ count: any; } | { count: any; deleteS: Stream<number>; })[]' is not assignable to type '[ReactivesObject, {}]'.
                  Property '0' is missing in type '({ count: any; } | { count: any; deleteS: Stream<number>; })[]'.

ERROR in ./src/version4.ts
(91,58): error TS2345: Argument of type 'Behavior<number[]>' is not assignable to parameter of type 'Behavior<number[]>'.

ERROR in ./src/version4.ts
(96,38): error TS2344: Type 'ToView' does not satisfy the constraint 'ReactivesObject'.
  Property 'counterIds' is incompatible with index signature.
    Type 'Behavior<number[]>' is not assignable to type 'Behavior<any> | Stream<any>'.
      Type 'Behavior<number[]>' is not assignable to type 'Stream<any>'.
        Property 'combine' is missing in type 'Behavior<number[]>'.

ERROR in ./src/version3.ts
(42,17): error TS2453: The type argument for type parameter 'V' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'CounterModelInput' is not a valid type argument because it is not a supertype of candidate '{} & OutputStream<{}> & BehaviorOutput<{}> & DefaultOutput'.
    Property 'incrementClick' is missing in type '{} & OutputStream<{}> & BehaviorOutput<{}> & DefaultOutput'.

ERROR in ./src/version3.ts
(66,44): error TS2345: Argument of type 'Behavior<number[]>' is not assignable to parameter of type 'Behavior<number[]>'.
  Types of property 'child' are incompatible.
    Type 'Observer<any>' is not assignable to type 'Observer<any>'. Two different types with this name exist, but they are unrelated.

ERROR in ./src/version3.ts
(70,49): error TS2345: Argument of type '({sum, counterIds}: ViewInput) => Iterator<Component<any>>' is not assignable to parameter of type 'View1<ReactivesObject, ModelInput, {}>'.
  Types of parameters '__0' and 'm' are incompatible.
    Type 'ReactivesObject' is not assignable to type 'ViewInput'.
      Property 'counterIds' is missing in type 'ReactivesObject'.

ERROR in ./src/version2.ts
(34,17): error TS2453: The type argument for type parameter 'V' cannot be inferred from the usage. Consider specifying the type arguments explicitly.
  Type argument candidate 'CounterModelInput' is not a valid type argument because it is not a supertype of candidate '{} & OutputStream<{}> & BehaviorOutput<{}> & DefaultOutput'.
    Property 'incrementClick' is missing in type '{} & OutputStream<{}> & BehaviorOutput<{}> & DefaultOutput'.

ERROR in ./src/index.ts
(25,17): error TS2345: Argument of type '{ class: string; classToggle: { active: Behavior<boolean>; }; }' is not assignable to parameter of type 'InitialProperties'.
  Types of property 'classToggle' are incompatible.
    Type '{ active: Behavior<boolean>; }' is not assignable to type '{ [name: string]: boolean | Behavior<boolean>; }'.
      Property 'active' is incompatible with index signature.
        Type 'Behavior<boolean>' is not assignable to type 'boolean | Behavior<boolean>'.
          Type 'Behavior<boolean>' is not assignable to type 'Behavior<boolean>'. Two different types with this name exist, but they are unrelated.
            Types of property 'child' are incompatible.
              Type 'Observer<any>' is not assignable to type 'Observer<any>'. Two different types with this name exist, but they are unrelated.
                Property 'changeStateDown' is missing in type 'Observer<any>'.

ERROR in ./src/index.ts
(28,29): error TS7031: Binding element 'click' implicitly has an 'any' type.

ERROR in ./src/index.ts
(32,3): error TS2345: Argument of type '({selectVersion}: { selectVersion: any; }) => Now<{ selected: Behavior<string>; }[]>' is not assignable to parameter of type 'Model1<{}, ReactivesObject, {}, {}>'.
  Type 'Now<{ selected: Behavior<string>; }[]>' is not assignable to type 'ModelReturn<ReactivesObject, {}>'.
    Type 'Now<{ selected: Behavior<string>; }[]>' is not assignable to type 'Iterator<Now<any> | [ReactivesObject, {}]>'.
      Property 'next' is missing in type 'Now<{ selected: Behavior<string>; }[]>'.

ERROR in ./src/index.ts
(36,15): error TS7031: Binding element 'selected' implicitly has an 'any' type.

ERROR in ./src/index.ts
(43,16): error TS2345: Argument of type '() => IterableIterator<Component<Stream<"1" | "2" | "3" | "4">> | { selectVersion: any; }>' is not assignable to parameter of type 'Child<{}>'.
  Type '() => IterableIterator<Component<Stream<"1" | "2" | "3" | "4">> | { selectVersion: any; }>' is not assignable to type '() => Iterator<Component<any>>'.
    Type 'IterableIterator<Component<Stream<"1" | "2" | "3" | "4">> | { selectVersion: any; }>' is not assignable to type 'Iterator<Component<any>>'.
      Types of property 'next' are incompatible.
        Type '(value?: any) => IteratorResult<Component<Stream<"1" | "2" | "3" | "4">> | { selectVersion: any; }>' is not assignable to type '(value?: any) => IteratorResult<Component<any>>'.
          Type 'IteratorResult<Component<Stream<"1" | "2" | "3" | "4">> | { selectVersion: any; }>' is not assignable to type 'IteratorResult<Component<any>>'.
            Type 'Component<Stream<"1" | "2" | "3" | "4">> | { selectVersion: any; }' is not assignable to type 'Component<any>'.
              Type '{ selectVersion: any; }' is not assignable to type 'Component<any>'.
                Object literal may only specify known properties, and 'selectVersion' does not exist in type 'Component<any>'.
webpack: Failed to compile.
```

**Comment by paldepind** [comment]
The `package.json` in the counters directory accidentally contained an old version of Hareactive. I've fixed that.

But, I've now encountered a new problem. I can only get the examples to work with the content of an old `node_modules` directory. It seems like some update to a dependency is causing some weird Webpack bug which breaks the examples.

**Comment by paldepind** [comment]
I've downgraded the dependencies in the counter example to some exact versions. It should work now :smile:

**Comment by dmitriz** [comment]
Unfortunately the problems remain for all the other examples.

I have also noticed errors when attempting to run typescript even for the simple example:

```sh
tsc -v
Version 2.3.2

tsc index.ts 
error TS2318: Cannot find global type 'IterableIterator'.
node_modules/@funkia/jabz/monad.d.ts(27,61): error TS2304: Cannot find name 'Iterator'.
node_modules/@funkia/jabz/monad.d.ts(28,51): error TS2304: Cannot find name 'Iterator'.
../../node_modules/@funkia/jabz/monad.d.ts(27,61): error TS2304: Cannot find name 'Iterator'.
../../node_modules/@funkia/jabz/monad.d.ts(28,51): error TS2304: Cannot find name 'Iterator'.
../../src/component.ts(21,70): error TS2304: Cannot find name 'Iterator'.
../../src/component.ts(34,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.
../../src/component.ts(104,31): error TS2304: Cannot find name 'Proxy'.
../../src/component.ts(123,44): error TS2304: Cannot find name 'IterableIterator'.
../../src/component.ts(142,26): error TS2304: Cannot find name 'Proxy'.
../../src/component.ts(166,14): error TS2304: Cannot find name 'Proxy'.
../../src/component.ts(178,47): error TS2304: Cannot find name 'Iterator'.
../../src/component.ts(181,60): error TS2304: Cannot find name 'Iterator'.
../../src/component.ts(182,76): error TS2304: Cannot find name 'Iterator'.
../../src/component.ts(230,12): error TS2304: Cannot find name 'Iterator'.
../../src/component.ts(251,45): error TS2304: Cannot find name 'Iterator'.
../../src/dom-builder.ts(283,15): error TS2304: Cannot find name 'Generator'.
../../src/dom-builder.ts(284,72): error TS2304: Cannot find name 'Generator'.
```

**Comment by paldepind** [comment]
I have now changed the way dependencies and configuration are handled for the examples.

Now they should all work. They have to be run in a slightly different way. [See the instructions here](https://github.com/funkia/turbine/tree/master/examples).

Please let me know if it works.

**Comment by dmitriz** [comment]
Thanks, love the precision! :)

A tiny correction - you mean `npm run ${name}`

All examples seem to work, the last 2 still throwing errors though,
and the todos example bundle seems to take forever to compile for some reason...

```sh
nr zip-codes

> turbine-examples@1.0.0 zip-codes /Users/dmitrizaitsev/Repos/turbine/examples
> webpack-dev-server --content-base zip-codes zip-codes/index.ts

Project is running at http://localhost:8080/
webpack output is served from /
Content not from webpack is served from /Users/dmitrizaitsev/Repos/turbine/examples/zip-codes
ts-loader: Using typescript@2.3.2 and /Users/dmitrizaitsev/Repos/turbine/examples/zip-codes/tsconfig.json
webpack: wait until bundle finished: /
Hash: 8e62756842cd07299b45
Version: webpack 2.2.1
Time: 5444ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  615 kB       0  [emitted]  [big]  main
chunk    {0} bundle.js (main) 535 kB [entry] [rendered]
   [15] ./zip-codes/~/@funkia/jabz/dist/es/applicative.js 3.09 kB {0} [built]
   [25] ./zip-codes/~/@funkia/jabz/dist/es/index.js 389 bytes {0} [built]
   [29] ../src/component.ts 11 kB {0} [built]
   [34] ./zip-codes/~/@funkia/jabz/dist/es/either.js 3.04 kB {0} [built]
   [35] ./zip-codes/~/@funkia/jabz/dist/es/foldable.js 4.33 kB {0} [built]
   [71] ./zip-codes/index.ts 1.94 kB {0} [built] [1 error]
   [72] (webpack)-dev-server/client?http://localhost:8080 5.28 kB {0} [built]
   [76] ../src/index.ts 313 bytes {0} [built]
  [115] ./~/strip-ansi/index.js 161 bytes {0} [built]
  [116] ./~/url/url.js 23.3 kB {0} [built]
  [118] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
  [119] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
  [121] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [123] ./zip-codes/~/@funkia/hareactive/index.js 459 bytes {0} [built]
  [143] multi (webpack)-dev-server/client?http://localhost:8080 ./zip-codes/index.ts 40 bytes {0} [built]
     + 129 hidden modules

ERROR in ./zip-codes/index.ts
(71,24): error TS2344: Type 'ToView' does not satisfy the constraint 'ReactivesObject'.
  Property 'status' is incompatible with index signature.
    Type 'Behavior<string>' is not assignable to type 'Behavior<any> | Stream<any>'.
      Type 'Behavior<string>' is not assignable to type 'Stream<any>'.
        Property 'combine' is missing in type 'Behavior<string>'.
webpack: Failed to compile.
```

**Comment by paldepind** [comment]
> A tiny correction - you mean `npm run ${name}`

Yes. Thank you. I've corrected it.

> the todos example bundle seems to take forever to compile for some reason...

Wierd. It seems to compile reasonably fast for me.

I'll close the issue now as all the examples works even though a few of them still gives type errors.
